name: Build SaveEditor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Lazarus
        uses: gcarreno/setup-lazarus@v3
        with:
          lazarus-version: "stable"

      - name: Build Project
        run: lazbuild -B SaveEditor.lpi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SaveEditor-Windows
          path: SaveEditor.exe
